Algoritmo "EXERCICIO5LISTA2"

Var
n1, n2, n3, n4, n5: inteiro
media: real

Inicio
escreval("Escreva 5 numeros:")
leia(n1)
leia(n2)
leia(n3)
leia(n4)
leia(n5)

media <- (n1+n2+n3+n4+n5)/5
escreval("Média: ",media)
se (n1>media) entao
   escreva(n1)
fimse
se (n2>media) entao
   escreva(n2)
fimse
se (n3>media) entao
   escreva(n3)
fimse
se (n4>media) entao
   escreva(n4)
fimse
se (n5>media) entao
   escreva(n5)
fimse



Fimalgoritmo