Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2026
Var
tempC, tempF: inteiro


Inicio
escreva("Digite a temperatura em graus Fahrenheit: ")
leia(tempF)
escreva((tempF-32)*(5/9), " graus Celsius")


Fimalgoritmo