Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2026
Var
vi, a, t: real

Inicio
escreva("Velocidade inicial em m/s: ")
leia(vi)
escreva("Aceleração em m/s: ")
leia(a)
escreva("Tempo em segundos: ")
leia(t)
escreva(vi+a*t, "m/s")

Fimalgoritmo
