Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2026
Var
width, length, watt: real

Inicio
escreva("Largura do cômodo em metros: ")
leia(width)
escreva("Comprimento do cômodo em metros: ")
leia(length)
escreva("Potência da lâmpada em watts: ")
leia(watt)
escreva("Precisa de", (18*(width*length))/watt, " lâmpadas")
Fimalgoritmo
