Algoritmo "exercicio1Lista2"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/08/2026
Var
num: real


Inicio
escreva("Escreva um numero de 1 a 9: ")
leia(num)
se (1<=num) e (num<=9) entao
   escreval("O valor está na faixa permitida")
senao
   escreval("O valor está fora da faixa permitida")
fimse
Fimalgoritmo
