Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
min, max, f: inteiro
c: real
Inicio
escreva("Escreva o menor número do intervalo em f: ")
leia(min)
escreva("Escreva o maior número do intervalo em f: ")
leia(max)
f <- min
enquanto f<=max faca
c <- ((5*f-160)/9))
escreval(f, "°F =", c:6:2, "°C")
f <- f+2
fimenquanto


Fimalgoritmo