Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2026
Var
dist, time: real
pilot: caractere

Inicio
escreva("Nome do piloto: ")
leia(pilot)
escreva("Distancia percorrida em km: ")
leia(dist)
escreva("Tempo para percorrer a distancia: ")
leia(time)
escreva("A velocidade média do ", pilot, " foi ", dist/time, "km/h.")

Fimalgoritmo