Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2026
Var
cashHour, hours: real
name: caractere

Inicio
escreva("Nome do funcionário: ")
leia(name)
escreva("Salário por hora: ")
leia(cashHour)
escreva("Horas trabalhadas: ")
leia(hours)
escreva("O salário de ", name, " é ", cashHour*hours, "R$")

Fimalgoritmo