Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2026
Var
r, h: real

Inicio
escreva("Raio: ")
leia(r)
escreva("Altura: ")
leia(h)
escreva("O volume do cilindro é: ", 3.14*r*r*h)

Fimalgoritmo